### PR TITLE
Split headline title to allow highlighting todo keywords.

### PR DESCRIPTION
**Pull request by kristijanhusak**
I know that you removed this few commits ago, but I don't think there is a way to get a chunk of the capture, even with the custom directive, because treesitter highlighter does not even respect the `#offset` directive. 
Since todo keywords are configurable and dynamic (both keywords and their colors), this allows to add highlights for the first word in headline if it's matching the configuration.

Edit: Here's how I do it with this solution: https://github.com/kristijanhusak/orgmode.nvim/blob/feature/ts/lua/orgmode/colors/todo_highlighter.lua#L30-L34

### CODE REVIEW

**Comment by emiasims** [comment]
What advantage does this add over simply using a query? `(headline (item) @keyword (#match? @keyword "^TODO\>"))` (might need to escape the backslash there, depending on how you're using it). This is very easily generated based on the user's keywords.

Adding a named node feels like it's polluting the tree unnecessarily, and we'd be querying over it anyway.

**Comment by kristijanhusak** [comment]
This allows highlighting only the TODO keyword (TODO, DONE, or whatever custom todo keyword is added) of the headline.
With your query,currently it highlights the whole headline. 

Here's example screenshot of current functionality with query similar to yours (OrgTODO is name of my hl group for todo keywords):

```
(headline (item) @OrgTODO (#match? @OrgTODO "^TODO\>"))
```

screenshot-before

And this is with applied changes and slightly adjusted query:

```
(headline (item (first) @OrgTODO) (#eq? @OrgTODO "TODO"))
```

screenshot-after

AFAIK Neovim's highlighter (at this moment on master), is not capable of highlighting parts of the nodes (with `#offset!` for example), so I don't think there is a way to achieve this without adding these to the tree.

**Comment by emiasims** [comment]
Understood. I'm still somewhat against adding it as a named node, because we should be able to query it like: `(headline (item . _ @keyword))`, where now the capture only matches the first node (which matches a _text node), but it looks like that style of anonymous node isn't working right now. Maybe the solution is to suck it up and temporarily add the named node. Honestly, I'd rather just use a different highlighting solution though (extmark is straightforward)

I'll dig a bit into the tree-sitter and neovim repo to find out why that query isn't working.

**Comment by kristijanhusak** [comment]
I did initially create a solution with a custom decoration provider that highlights these, but I thought this is a better solution. If you think this will cause a lot of issues, I can use that solution, at least until Neovim supports these "first node" queries.

**Comment by kristijanhusak** [comment]
Note to self: Fix the tests if this gets approved.

**Comment by emiasims** [comment]
Okay I think you're right. I still don't like it as a named node, but from a maintenance point of view (if/when anonymous nodes can be matched via queries), then you/anyone who uses this parser just need to change the query that finds the keyword and title, rather than changing the implementation completely.

Is the 'rest' required or can we get away with just the first node?

**Comment by kristijanhusak** [comment]
First one is enough, everything else can be easily used as `item`. I'll update it.

**Pull request merged**
